apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-ui-https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - cd.govirto.com
    secretName: argocd-secret
  rules:
  - host: cd.govirto.com
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http