apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-ui-https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - argo.govirto.com
    secretName: argocd-secret
  rules:
  - host: argo.govirto.com
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http