apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-ui
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: argocd-https-redirect@kubernetescrd
spec:
  tls:
  - hosts:
    - cd.virtoway.us
    secretName: argocd-secret
  rules:
  - host: cd.virtoway.us
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress-http
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: argocd-https-redirect@kubernetescrd
spec:
  rules:
  - host: cd.virtoway.us
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: http
