apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-cd-cert
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  secretName: argocd-secret
  issuerRef:
    name: argo-cd-issuer
    kind: Issuer
  commonName: cd.govirto.com
  dnsNames:
  - cd.govirto.com