apiVersion: v1
data:
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  ga.trackingid: 'TODO'
  url: https://cd.govirto.com
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: ed45580cb97cc9608f25
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: VirtoCommerce
          teams:
          - Virto Operations
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:admin
  policy.csv: |
    g, virtocommerce:virto operations, role:admin