apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  admin.enabled: 'true'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  ga.trackingid: 'UA-490257-44'
  url: https://argo.govirto.com/
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: d7f47a805b87566e8703
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: cloud-nation
          teams:
          - developers
          - operations