apiVersion: v1
data:
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  ga.trackingid: 'TODO'
  url: https://cd.govirto.com
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: ed45580cb97cc9608f25
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: virtocommerce
          teams:
          - virto-operations
kind: ConfigMap
metadata:
  name: argocd-cm