apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: init-sensor
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: update-modules-cm
      eventSourceName: resource
      eventName: platform-configmap-update
    # - name: update-app
    #   eventSourceName: resource
    #   eventName: app-update
  triggers:
    - template:
        conditions: "update-modules-cm # && - AND / || - OR "test-dep || test-dep1"
        name: init-platform-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: init-platform-
              spec:
                entrypoint: init-platform
                arguments:
                  parameters:
                  - name: resource
                    value: "JSON"
                workflowTemplateRef:
                  name: init-platform-template
          parameters:
            - src:
                dependencyName: update-modules-cm
                dataKey: body
              dest: spec.arguments.parameters.0.value