apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: init-platform-template
spec:
  arguments:
    parameters:
      - name: resource
        value: "JSON"
  templates:
    - name: init-platform
      inputs:
        parameters:
          - name: resource
      steps:
      - - name: parse
          template: parser
          arguments:
            parameters:
            - name: json
              value: "{{inputs.parameters.resource}}"
      - - name: install-modules
          template: install-modules 
          arguments:
            parameters:
            - name: app_name
              value: "{{steps.parse.outputs.parameters.app_name}}"
            - name: app_namespace
              value: "{{steps.parse.outputs.parameters.app_namespace}}"

    - name: parser
      inputs:
        parameters:
          - name: json
      container:
        image: kkisilevsky/alpine-jq
        command: [sh, -c]
        args:
          - "echo -n '{{inputs.parameters.json}}' | jq -r '.metadata.name' > /tmp/app_name.txt
          && echo '{{inputs.parameters.json}}' | jq -r '.spec.metadata.namespace' > /tmp/app_namespace.txt"
      outputs:
        parameters:
          - name: app_name
            valueFrom:
              path: /tmp/app_name.txt
          - name: app_namespace       
            valueFrom:
              path: /tmp/app_namespace.txt

    - name: install-modules
      inputs:
        parameters:
          - name: app_name
          - name: app_namespace
      container:
        image: kkisilevsky/alpine-jq
        command: [sh, -c]
        args:
          - "echo '{{inputs.parameters.app_name}}'
          && echo '{{inputs.parameters.app_namespace}}'"