kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "rook-nfs-share-retain"