apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cadvisor-metrics
  name: cadvisor-metrics
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: cadvisor