apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-qa-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/qa
    repoURL: https://github.com/virtocommerce/vc-deploy-apps
    targetRevision: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-s-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/develop
    repoURL: https://github.com/omnidark/sandbox
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 