apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/demo
    repoURL: https://github.com/VirtoCommerce/vc-composer-deploy
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composer-dev-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/dev
    repoURL: https://github.com/VirtoCommerce/vc-composer-deploy
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/dev
    repoURL: https://github.com/virtocommerce/vc-deploy-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-s-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/develop
    repoURL: https://github.com/omnidark/sandbox
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore-dev-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/dev
    repoURL: https://github.com/VirtoCommerce/vc-webstore-deploy
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore-qa-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/qa
    repoURL: https://github.com/VirtoCommerce/vc-webstore-deploy
    targetRevision: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore-demo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/demo
    repoURL: https://github.com/VirtoCommerce/vc-webstore-deploy
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-demo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/demo
    repoURL: https://github.com/VirtoCommerce/vc-deploy-saas
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace-demo-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/demo
    repoURL: https://github.com/VirtoCommerce/vc-deploy-marketplace
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace-dev-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app
  source:
    path: apps-config/overlays/dev
    repoURL: https://github.com/VirtoCommerce/vc-deploy-marketplace
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true