apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cert-manager
    repoURL: https://github.com/virtocommerce/vc-deploy-infra
    targetRevision: main
  ignoreDifferences:
    - group: apiextensions.k8s.io
      jsonPointers:
      - /status
      kind: CustomResourceDefinition  