apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: tenant-app-of-apps
  source:
    path: demo-apps
    repoURL: https://github.com/virtocommerce/vc-deployments
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true