apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: linkerd-loadtest-data-plane
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  readOnlyRootFilesystem: true
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  - NET_BIND_SERVICE
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loadtest-psp
  namespace: loadtest
rules:
- apiGroups: ['policy','extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['linkerd-loadtest-data-plane']
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadtest-psp
  namespace: loadtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: loadtest-psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: loadtest
- kind: ServiceAccount
  name: emoji
  namespace: loadtest
- kind: ServiceAccount
  name: voting
  namespace: loadtest
- kind: ServiceAccount
  name: web
  namespace: loadtest
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
  annotations:
    argocd.argoproj.io/sync-wave: "-1"