apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/virtocommerce/vc-deploy-infra
    targetRevision: google-cloud-platform
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition