apiVersion: v1
kind: ResourceQuota
metadata:
  name: saas-compute-resources
  namespace: saas
spec:
  hard:
    limits.memory: 8Gi
    pods: "16"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-compute-resources
  namespace: prod
spec:
  hard:
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-compute-resources
  namespace: demo
spec:
  hard:
    limits.memory: 16Gi
    pods: "20"