apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  annotations:
    argocd.argoproj.io/sync-wave: "-1"       
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hashicorp-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: saas
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: traefik
    annotations:
      argocd.argoproj.io/sync-wave: "-1" 
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: rook-ceph
    annotations:
      argocd.argoproj.io/sync-wave: "-1" 
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: rook-nfs-system
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: secret-generator
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: vault-dev
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: kube-logging
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: argo
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cadvisor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
