apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-compute-resources
  namespace: dev
spec:
  hard:
    limits.memory: 6Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: saas-compute-resources
  namespace: saas
spec:
  hard:
    limits.memory: 4Gi
    pods: "16"