apiVersion: v1
kind: LimitRange
metadata:
  name: saas-limit-range
  namespace: saas
spec:
  limits:
  - default:
      cpu: 125m
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
      cpu: 30m
    max:
      memory: 3Gi
    min:
      memory: 64Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limit-range
  namespace: prod
spec:
  limits:
  - default:
      cpu: 125m
      memory: 256Mi
    defaultRequest:
      cpu: 30m
      memory: 64Mi
    max:
      memory: 3Gi
    min:
      memory: 64Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limit-range
  namespace: demo
spec:
  limits:
  - default:
      cpu: 125m
      memory: 1024Mi
    defaultRequest:
      memory: 256Mi
      cpu: 30m
    max:
      memory: 3Gi
    min:
      memory: 64Mi
    type: Container 