apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hashicorp-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: saas
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: traefik
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
      scheduler.alpha.kubernetes.io/node-selector: agentpool=primary
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: rook-nfs-system
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: secret-generator
    annotations:
      argocd.argoproj.io/sync-wave: "-1" 
