apiVersion: v1
kind: LimitRange
metadata:
  name: saas-limit-range
  namespace: saas
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 64Mi
    max:
      memory: 3Gi
    min:
      memory: 64Mi
    type: Container    