apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  