apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 64Mi
    max:
      memory: 4Gi
    min:
      memory: 64Mi
    type: Container