apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: saas
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: rook-nfs-system
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: secret-generator
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: vault
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
