apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
apiVersion: v1
kind: Namespace
metadata:
  name: topolvm-system
  labels:
    app.kubernetes.io/name: topolvm-system
    control-plane: "true"
    topolvm.cybozu.com/webhook: ignore
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    