apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-tenant
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: prod
    server: '*'
  - namespace: demo
    server: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  orphanedResources:
    warn: false
  roles:
  - name: admin
    groups:
    - VirtoCommerce
    policies:
    - p, proj:prod-tenant:admin, applications, *, prod-tenant/*, allow