apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: saas-tenant
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: saas
    server: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  orphanedResources:
    warn: false
  roles:
  - name: admin
    groups:
    - VirtoCommerce
    policies:
    - p, proj:saas-tenant:admin, applications, *, saas-tenant/*, allow
    jwtTokens:
    - iat: 1612438277
      id: saas-token