apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://helm.mittwald.de'
    targetRevision: 3.1.0
    chart: kubernetes-secret-generator
    helm:
      parameters:
      - name: secretLength
        value: "12"
      - name: watchNamespace
        value: ""