apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: dev
    server: 'https://aks-f783f1e0.hcp.westus.azmk8s.io:443'
  - namespace: develop
    server: 'https://aks-f783f1e0.hcp.westus.azmk8s.io:443'
  - namespace: qa
    server: 'https://aks-f783f1e0.hcp.westus.azmk8s.io:443'
  - namespace: dev
    server: 'https://kubernetes.default.svc'
  - namespace: develop
    server: 'https://kubernetes.default.svc'
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: 'networking.k8s.io'
    kind: NetworkPolicy
  orphanedResources:
    warn: false
  roles:
  - name: admin
    groups:
    - VirtoCommerce
    policies:
    - p, proj:tenant:admin, applications, *, tenant/*, allow