apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: topolvm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/virtocommerce/vc-deploy-infra
    targetRevision: HEAD
    path: topolvm/base
  destination:
    server: https://kubernetes.default.svc
    namespace: topolvm-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
