apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/virtocommerce/vc-deploy-infra
    targetRevision: main
    path: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp-vault
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    jsonPointers:
    - /status
    kind: MutatingWebhookConfiguration