apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meds-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: meds-demo
    repoURL: https://github.com/virtocommerce/vc-deployments
    targetRevision: HEAD