apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webstore-demo
    repoURL: https://github.com/virtocommerce/vc-deployments
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    