apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=crd
        - --domain-filter=dev.govirto.com
        - --provider=google
        - --google-project=rpj
        - --registry=txt
        - --txt-owner-id=virto
        - --log-format=json
