apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/install.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        agentpool: primary
  target:
    group: apps
    version: v1
    kind: Deployment