apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-platform-web
spec:
  template:
    spec:
      containers:
        - name: vc-platform-web
          env:
          - name: Assets__FileSystem__PublicUrl
            value: "http://vc-meds-dev-backoffice.westus.cloudapp.azure.com/cms-content/assets/"
          - name: Content__FileSystem__PublicUrl
            value: "http://vc-meds-dev-backoffice.westus.cloudapp.azure.com/cms-content/"