apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic-exporter
  name: elastic-metrics
spec:
  ports:
  - name: http
    port: 9114
    protocol: TCP
    targetPort: 9114
  selector:
    app: elastic-exporter