apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elastic-server-metrics
  labels:
    app: elastic-exporter
spec:
  selector:
    matchLabels:
      app: elastic-exporter
  endpoints:
  - port: http