apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webstore-demo
  namespace: demo
spec:
  destination:    
    namespace: kustomize-guestbook
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: webstore-demo
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}