apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-domain
spec:
  secretName: wildcard-domain-tls-secret
  issuerRef:
	name: letsencrypt-wild
	kind: ClusterIssuer
  commonName: '*.dev.company.de'
  dnsNames:
  - '*.dev.company.de'
  acme:
	config:
	- dns01:
		provider: azure-dns
	  domains:  
	  - '*.dev.company.de'