apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-content-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 100Mi