apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modules-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 200Mi