apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base

patchesStrategicMerge:
- overlays/argo-cd-cm.yaml
- overlays/argocd-server-service.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd