apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: curator
spec:
  arguments:
    parameters:
      - name: scope
        value: hello world
  templates:
    - name: curator-template
      resource:
        action: create
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            generateName: curator-
          spec:
            template:
              metadata:
                name: curator
              spec:
                containers:
                - name: curator
                  image: kkisilevsky/curator
                  name: curator
                  env:
                    - name: SCOPE
                      value: "{{inputs.parameters.scope}}"
                  command:
                    - "/bin/sh"
                    - "-c"
                  args:
                    - "sudo envsubst '$${SCOPE}'< /etc/config/action_file.yml.template > /etc/config/action_file.yml 
                    && cat /etc/config/action_file.yml
                    && /usr/bin/curator --config /etc/config/config.yml /etc/config/action_file.yml"
                  volumeMounts:
                  - name: config
                    mountPath: /mnt
                    readOnly: false
                volumes:
                - name: config
                  configMap:
                    name: curator-config
                restartPolicy: Never
      inputs:
        parameters:
          - name: scope
      # container:
      #   image: bobrik/curator:5.8.1
      #   command: [cowsay]
      #   args: ["{{inputs.parameters.message}}"]