apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: curator
spec:
  arguments:
    parameters:
      - name: scope
        value: hello world
  templates:
    - name: curator-template
      resource:
        action: create
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            generateName: curator-
          spec:
            template:
              metadata:
                name: curator
              spec:
                containers:
                - name: rand
                  image: alpine:3.7
                  command: [echo, "{{inputs.parameters.scope}}"]
                restartPolicy: Never
      inputs:
        parameters:
          - name: scope
      # container:
      #   image: docker/whalesay
      #   command: [cowsay]
      #   args: ["{{inputs.parameters.message}}"]