apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base/install.yaml
- workflows/curator/curator-configmap-template.yaml
- workflows/curator/curator.yaml
- workflows/db-remover/db-remover.yaml
- workflows/init-platform/init-platform.yaml
- webhook-template.yaml