apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base
- ./workflow-controller-rbac
- ./argo-server-rbac
- workflows/rollouts/rollouts-promoting.yaml
- workflows/rollouts/rbac.yaml
- workflows/curator/curator-configmap-template.yaml
- webhook-template.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        agentpool: primary
  target:
    group: apps
    version: v1
    kind: Deployment
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        agentpool: primary
  target:
    group: apps
    version: v1
    kind: StatefulSet