apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./base
- ./workflow-controller-rbac
- ./argo-server-rbac
- workflows/rollouts/rollouts-promoting.yaml
- workflows/rollouts/rbac.yaml
- webhook-template.yaml
