apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: resource
        value: "JSON"
  templates:
    - name: main
      inputs:
        parameters:
          - name: resource
      steps:
      - - name: parse
          template: parser
          arguments:
            parameters:
            - name: json
              value: "{{inputs.parameters.resource}}"
      - - name: print
          template: print-message
          arguments:
            parameters:
            - name: message
              value: "{{steps.parse.outputs.result}}"

    - name: parser
      inputs:
        parameters:
          - name: json
      container:
        image: kkisilevsky/alpine-jq
        command: [sh, -c]
        args:
          - "export APP_NAME=$(echo '{{inputs.parameters.json}}' | jq -r '.metadata.name')
          && export NAMESPACE=$(echo '{{inputs.parameters.json}}' | jq -r '.spec.destination.namespace')
          && echo $APP_NAME'-platform_'$NAMESPACE"

    - name: print-message
      inputs:
        parameters:
        - name: message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo '{{inputs.parameters.message}}'"]