apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: resource
        value: "JSON"
  templates:
    - name: creator
      inputs:
        parameters:
          - name: resource
      steps:
      - - name: parse
          template: parser
          arguments:
            parameters:
            - name: json
              value: "{{inputs.parameters.resource}}"
      - - name: create-database
          template: create-database-template
          arguments:
            parameters:
            - name: db_name
              value: "{{steps.parse.outputs.result}}"

      - name: remover
        inputs:
          parameters:
            - name: resource
        steps:
        - - name: parse
            template: parser
            arguments:
              parameters:
              - name: json
                value: "{{inputs.parameters.resource}}"
        - - name: remove-database
            template: remove-database-template
            arguments:
              parameters:
              - name: db_name
                value: "{{steps.parse.outputs.result}}"

    - name: parser
      inputs:
        parameters:
          - name: json
      container:
        image: kkisilevsky/alpine-jq
        command: [sh, -c]
        args:
          - "export APP_NAME=$(echo '{{inputs.parameters.json}}' | jq -r '.metadata.name')
          && export NAMESPACE=$(echo '{{inputs.parameters.json}}' | jq -r '.spec.destination.namespace')
          && echo $APP_NAME'-platform_'$NAMESPACE"

    - name: create-database-template
      inputs:
        parameters:
        - name: db_name
      container:
        image: mcr.microsoft.com/mssql-tools
        command:
          - "/opt/mssql-tools/bin/sqlcmd"
          - "-S"
          - "vc-dev-dbserver.database.windows.net"
          - "-U"
          - "virto@vc-dev-dbserver"
          - "-P"
          - "$(VC_DBSERVER_MASTER_PASSWORD)"
          - "-q"
          - "CREATE DATABASE [{{inputs.parameters.db_name}}] AS COPY OF [webstore-platform_source] ( SERVICE_OBJECTIVE = ELASTIC_POOL ( name = [vc-dev-elasticpool] ) )"
        env: 
          - name: VC_DBSERVER_MASTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vc-dbserver-password
                key: password
  
    - name: remove-database-template
      inputs:
        parameters:
        - name: db_name
      container:
        image: mcr.microsoft.com/mssql-tools
        command:
          - "/opt/mssql-tools/bin/sqlcmd"
          - "-S"
          - "vc-dev-dbserver.database.windows.net"
          - "-U"
          - "virto@vc-dev-dbserver"
          - "-P"
          - "$(VC_DBSERVER_MASTER_PASSWORD)"
          - "-q"
          - "DROP DATABASE [{{inputs.parameters.db_name}}]"
        env: 
          - name: VC_DBSERVER_MASTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vc-dbserver-password
                key: password