apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: resource
        value: "JSON"
  templates:
    - name: main
      dag:
        tasks:
          - name: a
            template: parser
            arguments:
              parameters:
                - name: resource
                  value: "{{inputs.parameters.resource}}"
          - name: b
            template: whalesay-template
            arguments:
              parameters:
                - name: message
                  value: "{{tasks.a.outputs.result}}"
            dependencies:
              - a

    - name: parser
      inputs:
        parameters:
          - name: resource
      containerSet:
        containers:
          - name: parser
            image: kkisilevsky/alpine-jq
            command:
            - "/bin/sh"
            - "-c"
            args:
              - "echo {{inputs.parameters.resource}} | jq -r '.metadata.name' 
              && echo {{inputs.parameters.resource}} | jq -r '.spec.destination.namespace'"

    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]