apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
spec:
  template:
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: cke.cybozu.com/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cke.cybozu.com/master
                    operator: Exists
