---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-us
provisioner: blob.csi.azure.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: azure-secret-us
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: azure-secret-us
  csi.storage.k8s.io/node-stage-secret-namespace: default
reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate