apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-cuplugs
provisioner: blob.csi.azure.com
parameters:
  resourceGroup: cloud-platform
  storageAccount: cuplugsblob  # cross subscription is not supported
  containerName: virtocomposer
reclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate