---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blob-premium
provisioner: blob.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain  # if set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate