apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: search-dev
  namespace: elastic-system
spec:
  version: 7.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - count: 1
    name: master-nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false