apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: search-dev
  namespace: elastic-system
spec:
  version: 7.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podDisruptionBudget:
    spec:
      minAvailable: 1
  nodeSets:
  - count: 2
    name: master-nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 16Gi
          storageClassName: managed-premium