apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress-https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: 
      - "kibana-dev.govirto.com"
      secretName: kibana-tls
  rules:
  - host: kibana-dev.govirto.com
    http:
      paths:
      - backend:
          serviceName: kibana-kb-http
          servicePort: 5601
        path: /