apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 7.4.2
  count: 1
  elasticsearchRef:
    name: search-dev
  podTemplate:
    spec:
      nodeSelector:
        agentpool: primary
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
        env:
          - name: SERVER_BASEPATH
            value: /app
  http:
    tls:
      selfSignedCertificate:
        disabled: true