apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream/all-in-one.yaml
#  - rbac.yaml
  - namespace.yaml
#  - elastic-deploy.yaml
#  - network.yaml  
#patchesStrategicMerge:
#  - statefulset.yaml
#  - crd.yaml
#  - validatingwebhookconfiguration.yaml
