apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: search-dev-es-elastic-user
  namespace: elastic-system
  literals:
  - elastic=virtodevpass
generatorOptions:
  disableNameSuffixHash: true