apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-wild
spec:
  commonName: '*.wild.govirto.com'
  dnsNames:
  - "*.wild.govirto.com"
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: support@virtocommerce.com
    privateKeySecretRef:
      name: letsencrypt-wild
    solvers:
    - dns01:
        azureDNS:  
          clientID: "33467df4-b33a-4c8a-b29f-8b5e8ce7916b"
          clientSecretSecretRef:
            key: client-secret
            name: azuredns-config
          hostedZoneName: "govirto.com"
          resourceGroupName: "dns"
          subscriptionID: "63624d02-de44-421b-9d19-306a8e26b322"
          tenantID: "bc03e660-5e3a-45c4-bf5c-b75489f78923"