apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard-domain
spec:
  secretName: wildcard-domain-tls-secret
  issuerRef:
    name: letsencrypt-wild
    kind: ClusterIssuer
  commonName: '*.wild.govirto.com'
  dnsNames:
  - '*.wild.govirto.com'
  acme:
    config:
    - dns01:
        provider: azuredns
      domains:
      - '*.wild.govirto.com'