apiVersion: apps/v1 
kind: Deployment
metadata:
  name: redis-master
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      nodeSelector:
          agentpool: primary
      containers:
      - name: master
        image: redis:5.0.9
        args: ["--requirepass", "$(REDIS_PASS)"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        env:
          - name: MASTER
            value: "true"
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: redis
                key: REDIS_PASS
          
              
        


